language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run emlesoauth sh -c "./wait-for-it.sh postgres:5432 -t 60 -- mvn clean test"
deploy:
  provider: heroku
  api_key:
    secure: "1ixJ7BfwCUC/lX2/Os/FMaBLBVgZJs3SQKs4pBuUIqAnwcmloQE4a2eyB3hhs8I4LHXFXgKhMBf3k3X7mDwQSgkuYhYNbsfb321j9ZJCDkT47rjgltPF5rrLUrkI0y0NkPrzHYgvXAFyF4ZV2JYUrSq9eCblqyakzMN0+6RCsWY7mpWmYcEOseBgYO1A4N8UdWqbDm1dbumbfLepKgz3sRLjFE9gjyl6CqikzITaGEDBJC0T4L4TkYE1DdAjm2LRq2DfE2cCjm3opCvLxNX3ncM55gdzsU6R5TTeWrgG+oM+JOFCT2HCm5ZRMjes7PqHlrvlVP0bswl6vbex+dvaSGKz74P1ZWdWlOkM0rG5fKuZ66Ob7k1jtncQycZScrvC1tTMwntZdTPi35B4WLiQcMzugSM88EDp34j/7VbPXtIKy6GliNFQ9Ei27b0guSfJAleIOqu0iCus76CpxNngasDCzsTBAJyKsCSMwHbjZLKVOR4C0zviFua9thYpNGU+xPHlSA3P/fj8Kne5D+w8v7cUyBJ/N8CMHPzoYlqEwOlfewyZUdnxE1Prz11+GCnfWtq234jOpcRurcG9aTJnglzBAPHJPxAGHKbc5tgvixSjTJ54yT2cpZC5QRY12WPYA37eic6gTRwOZTZVSO0v6TxJZ9Nnkft/GuXqYqd182k="
  on: master
  app: stormy-scrubland-49921