language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run emlesmono sh -c "./wait-for-it.sh postgres:5432 -t 60 -- mvn clean test"
deploy:
  provider: heroku
  api_key:
    secure: "2b7lP65uSQWV3EblhSRqQzxjBowf8BZZdK0nrJdfcvcyYsowXtL9hHqwr+CS0rx6TY96jP3/+HZoQBaSO1QIlwy4fA+coRCKdjqs2WyRRW7ze3eLQPRS5wTkZNmSXxYUzqvC7N8wjUUwsKxYTZs4KW5QoykSR8IOouQ8C6NK4uNYbPVTmQ9T1RLcFEi195sON7kUEccPzAuWK8zXLjnvPtrvdyLUTfKfeV4RBVOT4IS15ZXtZP9Mq/z7Otcft+4x6wK4czD/Wo2yUduN9KRdKMGCucGrPnJZQckEFYwseuRRhw8xW7IIc2VUJQ8p9lAjzlRneVYt5Bs5lATIeyObCYR33I21lzxDr9RRSI26rskI6jhOuKwuYKT9Zs6A5gqYmr0kcRC12cvYcegSB8km7/sjOBbipBfqtNPeCLUJIGfwknoNkefp7rZU+MSFl73J/kEbcRsg8eivMUmDlA20CoN7+QOsbF6a2+84SrVYYBgOjYEjOuFwqsawmvggmUaVsZySSBi8YaYF7LZlaprNrra5hq6ypQpAczPOS/TtS6gETcGz1WHV+oIIuMbInX8rJTHan6FLG2OU10Fxsur4vR8zIvNs0JoGu8mj6MiLkk8julNKCqqB4f1q9DNwjrVmXBmWkmzWlEd2qCOCNY/LpT4nB9w2yDIdnGwbrKEMSPg="
  on: master
  app: stormy-scrubland-49921